version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: CONTAINER_MYSQL_BANCODIGITAL_DESAFIOFULL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_BancoDigital
      MYSQL_USER: user
      MYSQL_PASSWORD: admin123
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: java-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
